addi        PASSED
add         PASSED
andi        PASSED
and         PASSED
auipc       PASSED
lui         PASSED
ori         PASSED
or          PASSED
rebouclage  PASSED
slli        PASSED
sll         PASSED
srai        PASSED
sra         PASSED
srli        PASSED
srl         PASSED
sub         PASSED
xori        PASSED
xor         PASSED
SLT         PASSED
SLTI        PASSED
SLTU        PASSED
SLTIU       PASSED
BLT         PASSED
BNE         PASSED
BEQ         PASSED
BGE         PASSED
BGEU        PASSED
BLTU        PASSED
